-- ScholarSite Database Schema for A2 Hosting PostgreSQL
-- Run this script in phpPgAdmin or via psql command line
-- No extensions required - UUIDs are generated by the application

-- Tenants table - each paying customer
CREATE TABLE IF NOT EXISTS tenants (
  id VARCHAR(36) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  plan VARCHAR(50) DEFAULT 'starter' NOT NULL,
  status VARCHAR(50) DEFAULT 'pending' NOT NULL,
  subscription_start_date TIMESTAMP,
  subscription_end_date TIMESTAMP,
  last_sync_at TIMESTAMP,
  sync_frequency VARCHAR(50) DEFAULT 'monthly',
  primary_color VARCHAR(20) DEFAULT '#0B1F3A',
  accent_color VARCHAR(20) DEFAULT '#F2994A',
  logo_url VARCHAR(500),
  contact_email VARCHAR(255),
  notes TEXT,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- Domains table - map custom domains to tenants
CREATE TABLE IF NOT EXISTS domains (
  id VARCHAR(36) PRIMARY KEY,
  tenant_id VARCHAR(36) NOT NULL REFERENCES tenants(id),
  hostname VARCHAR(255) UNIQUE NOT NULL,
  is_primary BOOLEAN DEFAULT false NOT NULL,
  is_subdomain BOOLEAN DEFAULT false NOT NULL,
  ssl_status VARCHAR(50) DEFAULT 'pending',
  verified_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT NOW()
);

-- Users table for authentication
CREATE TABLE IF NOT EXISTS users (
  id VARCHAR(36) PRIMARY KEY,
  tenant_id VARCHAR(36) REFERENCES tenants(id),
  email VARCHAR(255) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(50) DEFAULT 'researcher' NOT NULL,
  first_name VARCHAR(100),
  last_name VARCHAR(100),
  profile_image_url VARCHAR(500),
  is_active BOOLEAN DEFAULT true NOT NULL,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- Researcher profiles table
CREATE TABLE IF NOT EXISTS researcher_profiles (
  id VARCHAR(36) PRIMARY KEY,
  tenant_id VARCHAR(36) NOT NULL REFERENCES tenants(id),
  openalex_id VARCHAR(50) UNIQUE,
  display_name TEXT,
  title TEXT,
  bio TEXT,
  profile_image_url VARCHAR(500),
  cv_url VARCHAR(500),
  current_affiliation TEXT,
  current_position TEXT,
  current_affiliation_url VARCHAR(500),
  current_affiliation_start_date DATE,
  email VARCHAR(255),
  is_public BOOLEAN DEFAULT true,
  last_synced_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- OpenAlex researcher data cache
CREATE TABLE IF NOT EXISTS openalex_data (
  id VARCHAR(36) PRIMARY KEY,
  openalex_id VARCHAR(50) NOT NULL,
  data_type VARCHAR(50) NOT NULL,
  data JSONB NOT NULL,
  last_updated TIMESTAMP DEFAULT NOW(),
  UNIQUE(openalex_id, data_type)
);

-- Research topics cache
CREATE TABLE IF NOT EXISTS research_topics (
  id VARCHAR(36) PRIMARY KEY,
  openalex_id VARCHAR(50) NOT NULL,
  topic_id VARCHAR(50) NOT NULL,
  display_name TEXT NOT NULL,
  count INTEGER NOT NULL,
  subfield TEXT,
  field TEXT,
  domain TEXT,
  value VARCHAR(50)
);

-- Publications cache
CREATE TABLE IF NOT EXISTS publications (
  id VARCHAR(36) PRIMARY KEY,
  openalex_id VARCHAR(50) NOT NULL,
  work_id VARCHAR(50) NOT NULL,
  title TEXT NOT NULL,
  author_names TEXT,
  journal TEXT,
  publication_year INTEGER,
  citation_count INTEGER DEFAULT 0,
  topics JSONB,
  doi VARCHAR(255),
  is_open_access BOOLEAN DEFAULT false,
  publication_type VARCHAR(50),
  is_review_article BOOLEAN DEFAULT false
);

-- Affiliations cache
CREATE TABLE IF NOT EXISTS affiliations (
  id VARCHAR(36) PRIMARY KEY,
  openalex_id VARCHAR(50) NOT NULL,
  institution_id VARCHAR(50) NOT NULL,
  institution_name TEXT NOT NULL,
  institution_type VARCHAR(100),
  country_code VARCHAR(10),
  years JSONB,
  start_year INTEGER,
  end_year INTEGER
);

-- Site settings table
CREATE TABLE IF NOT EXISTS site_settings (
  id VARCHAR(36) PRIMARY KEY,
  setting_key VARCHAR(100) UNIQUE NOT NULL,
  setting_value TEXT NOT NULL,
  updated_at TIMESTAMP DEFAULT NOW()
);

-- Session table for express-session (connect-pg-simple)
CREATE TABLE IF NOT EXISTS "session" (
  "sid" VARCHAR NOT NULL COLLATE "default",
  "sess" JSON NOT NULL,
  "expire" TIMESTAMP(6) NOT NULL,
  PRIMARY KEY ("sid")
);

CREATE INDEX IF NOT EXISTS "IDX_session_expire" ON "session" ("expire");

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_domains_tenant ON domains(tenant_id);
CREATE INDEX IF NOT EXISTS idx_users_tenant ON users(tenant_id);
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_profiles_tenant ON researcher_profiles(tenant_id);
CREATE INDEX IF NOT EXISTS idx_profiles_openalex ON researcher_profiles(openalex_id);
CREATE INDEX IF NOT EXISTS idx_openalex_data_id ON openalex_data(openalex_id);
CREATE INDEX IF NOT EXISTS idx_topics_openalex ON research_topics(openalex_id);
CREATE INDEX IF NOT EXISTS idx_publications_openalex ON publications(openalex_id);
CREATE INDEX IF NOT EXISTS idx_affiliations_openalex ON affiliations(openalex_id);

-- Insert default admin user
-- ID is a pre-generated UUID
-- Password hash for 'Admin123!' using bcrypt with 12 rounds
INSERT INTO users (id, email, password_hash, role, first_name, last_name, is_active)
VALUES (
  '550e8400-e29b-41d4-a716-446655440000',
  'admin@scholarsite.com',
  '$2a$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/X4.VxHHFe4W9oA.Pu',
  'admin',
  'Platform',
  'Admin',
  true
) ON CONFLICT (email) DO NOTHING;
